version: '3'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - "server"

  server:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
